name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
           key: ${{secrets.GOOGLE_CLOUD_VM_SSH}}
        host: ${{secrets.GOOGLE_CLOUD_VM_IP}}
        username: ${{secrets.GOOGLE_CLOUD_VM_USERNAME}}
     
          script: |
            if [ -d "/var/app/tdd-nodejs/${{ secrets.APP_NAME }}" ]; then echo "Directory /var/app/tdd-nodejs/dir exists."; then git pull && cd /var/app/tdd-nodejs/${{ secrets.APP_NAME }} && pm2 restart ${{ secrets.APP_NAME }}; else cd /var/app/tdd-nodejs/ && git clone git@github.com:jspawar80/${{ secrets.APP_NAME }}.git && cd /var/app/tdd-nodejs/${{ secrets.APP_NAME }} && npm i && pm2 start index.js --name "${{ secrets.APP_NAME }}" &&  echo "Error: Directory /var/app/${{ secrets.APP_NAME }} dir does not exists."; fi

 
